{% set version = "4.3.2" %}

package:
  name: guiqwt
  version: {{ version }}

source:
  url: https://github.com/PierreRaybaut/guiqwt/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 83ec00fa402668ac39eb07494e45092be81d2a372630ed8527475dab737c2dae

build:
  skip: true  # [win and vc<14]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - guidata >=2.3
    - pyqt
  run:
    - guidata >=2.3
    - {{ pin_compatible('numpy') }}
    - pillow
    - python
    - pythonqwt >=0.10
    - qtpy >=1.3
    - scipy >=0.7

test:
  imports:
    - guiqwt
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PierreRaybaut/guiqwt
  license: CECILL-2.0
  license_family: OTHER
  license_file: Licence_CeCILL_V2-en.txt
  summary: Automatic GUI generation for easy dataset editing and display with Python
  description: |
    Based on PythonQwt (a pure Python/PyQt reimplementation of the curve
    plotting Qwt C++ library, included in guiqwt base source code) and on the
    scientific modules NumPy and SciPy, guiqwt is a Python library providing
    efficient 2D data-plotting features (curve/image visualization and related
    tools) for interactive computing and signal/image processing application
    development. It is based on Qt graphical user interfaces library, and
    currently supports both PyQt4 and PyQt5.
  doc_url: https://guiqwt.readthedocs.io
  dev_url: https://github.com/PierreRaybaut/guiqwt

extra:
  recipe-maintainers:
    - beenje
    - denivyruck
    - marcelotrevisani
