travis:
  secure:
    BINSTAR_TOKEN: O9EW/fEYbIuHbeDLhCKP3Clc7wJ5S8ScrIgE1wDfLTb5u9JEpjq2YlA34YQ49QCw/7RTvSa5FpHTrLSUTEN1PATQz2yPIJjww6wKVgCV5dCUoReaaNgATUA7GeY7qCE//JoGlhtprLFgQskfsAML8bYC8nG4fj9reGcNTDeIqyQjlZY1sJ5YgZ/3KLqRNQGQjW2s5J23mm1qdWDIEk84u1NTzJlLW1seXQZQ9jjAGH1hQ2/yb+I4cwv8lV57w56YAWqt0eV4mgbEy0TlX07Fuqyb4DZbgvSWlz8sz3l8MCZ2IXZmmVpEAXqBvOsWMzrp8FymP7sqQb/ibNBdgcJERGq0xvZRTt7vqHBZKYdFNj3Ful7X+inc7mRX2YFmLI15su4IK9N8KLg/9poTuKJ0rfYjOQ66c9YIpWteXO6Sib9NX5qzGEfD+aWp/PEv3N6CXVPLVDyLJjQh/McIQ/DUyqhBkJXfVsfbt4TJFa9BH3q8/YvQXMKdGlfTHQcQ9nFWIbqB4I97ekTM/JQEs1CZtledmqdSg7dBHmsshSKlIJ0kdPCeUAV0f2AhR8+4tZTdhybILVVJjPYGpXZT2cKIgcu4zyLnqg3OppcP6IK/D+0Q3U386QVHQby5EnYtrx5akMD5CVPs/YPnb6+8gkdFCLK0NX2Bm8+pf7bLzzkC0Vo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
